Repository Hysnap/Team5-Hackathon2, pull requests merged in 2025-02, with the labels that each got.

#24 Presentation - Blank from Vasi
  DBC Bootcamp Hackathon Presentation Template.pptx
Labels: 2 - documentation

#33 Updated Readme and added data file
  .gitignore
  BankChurners.csv
  README.md
  jupyter_notebooks/Notebook_Template_PG_Scratchpad.ipynb
Labels: 2 - documentation

#38 added chatgpt out
  ChatGPT output/Notebook_Template.ipynb
Labels: 2 - documentation

#39 adding more chatgpt output
  ChatGPT output/Notebook_Template.ipynb
Labels: 3 - Awaiting Review

#40 Rough Workings and simple Population Analysis in PowerBI
  .gitignore
  PowerPI_PopulationComparison.pbix
  jupyter_notebooks/Notebook_Template_PG_Scratchpad.ipynb
Labels: 2 - documentation, 3 - Awaiting Review

#55 ETL first commit
  .DS_Store
  BankChurners.csv
  BankChurners_Cleaned_Encoded.csv
  ETL hackathon2 ETL NEW.py
  ETL hackathon2.py
  hackathon2.ipynb
  jupyter_notebooks/Notebook_Template.ipynb
Labels: 1 - enhancement

#56 Refresh
  PowerPI_PopulationComparison.pbix
Labels: 2 - documentation

#57 Main
  ChatGPT output/Notebook_Template.ipynb
Labels: 1 - enhancement

#58 Main
  .gitignore
  jupyter_notebooks/Ewas_draft.ipynb
Labels: 1 - enhancement

#60 Main
  team5 assestment .twbx
Labels: 1 - enhancement

#61 Tableau visualisation draft
  Tableau_visualisation_e.twbx
Labels: 1 - enhancement

#74 Main
  .DS_Store
  Chat GPT output - t-tests and hypothesis testing.ipynb
  ChatGPT output for adult dataset transformation.ipynb
  adult_final.csv
  adult_renamed.csv
Labels: 1 - enhancement

#75 add dasboard in tableau
  team5 assestment .twbx
  ~team5 assestment __10164.twbr
Labels: 1 - enhancement

#77 Main
  Chat GPT output - t-tests and hypothesis testing.ipynb
  ChatGPT output for adult dataset transformation.ipynb
  adult_new_variables.csv
  t-tests_summary.csv
Labels: 2 - documentation, 1 - enhancement

#76 Getting level
  ~team5 assestment __27520.twbr
Labels: 2 - documentation

#79 Main
  .DS_Store
  adult database variable changes summary.ipynb
  adult variable and category mapping.csv
Labels: 2 - documentation, 1 - enhancement

#81 update
  Dashbord1.png
  Dashbord2.png
  team5 assestment .twbx
  ~team5 assestment __10164.twbr
Labels: 1 - enhancement

#82 Readme updated with information about dashboard
  README.md
  team5 assestment .twbx
  ~team5 assestment __1524.twbr
Labels: 2 - documentation

#84 final update
  README.md
Labels: 1 - enhancement
